### ISSUE TITLE
Undefined Reference to cv::CUDA when library is getting linked 

### ISSUE THREAD

**Issue by connorsoohoo** [yunchih/ORB-SLAM2-GPU2016-final#14]
I have the same error as #7  but I verified that I installed OpenCV with CUDA. I was previously getting this project to compile before I reflashed my Tx2 but I had to reflash my Tx2 and reinstall all the dependencies. I was originally getting issue #6 but after linking nvToolsExt to my /usr/lib folder I still can't see any CUDA references.

**Comment by connorsoohoo** [comment]
I had to reflash my Tx2 and reinstall to link the libraries properly.

**Comment by cbachhuber** [comment]
Also, as written in [Raul Mur-Artal's instructions](https://github.com/raulmur/ORB_SLAM2#opencv), ORB-SLAM only works with OpenCV 3.1.0 out of the box. You can check your OpenCV version in `/usr/local/include/opencv2/core/version.hpp`, where for example

```
#define CV_VERSION_MAJOR    3
#define CV_VERSION_MINOR    4
#define CV_VERSION_REVISION 1
```

stands for OpenCV 3.4.1. ORB-SLAM also works fine with OpenCV 3.4.1, you just have to replace the [line](https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/CMakeLists.txt#L44)

```
find_package(OpenCV 3.1.0 REQUIRED)
```

of [CMakeLists.txt](https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/CMakeLists.txt) by

```
find_package(OpenCV 3.0 QUIET)
if(NOT OpenCV_FOUND)
   find_package(OpenCV 2.4.3 QUIET)
   if(NOT OpenCV_FOUND)
      message(FATAL_ERROR "OpenCV > 2.4.3 not found.")
   endif()
endif()
```

**Comment by cbachhuber** [comment]
Right! Later I also saw the conflict with the ROS version, so I ended up replacing the above mentioned [line](https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/CMakeLists.txt#L44) by

```
find_package(OpenCV REQUIRED
    NO_MODULE
    PATHS /usr/local/include
NO_DEFAULT_PATH)
```

as described in the [ROS answers](https://answers.ros.org/question/242376/having-trouble-using-cuda-enabled-opencv-with-kinetic/?answer=242935#post-id-242935). This method avoids that cmake is searching for OpenCV in the ROS directories.
